---
title: "Homework8"
author: "Devin Etcitty"
date: "April 29, 2017"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(alr4)
library(ggplot2)
```

## Problem 9.18

```{r}
head(cloud)
```

```{r}
cloud$A <- as.factor(cloud$A)
```



```{r}
plot(cloud)
```

```{r}
ggplot(cloud, aes(A)) +
  geom_bar()
```



```{r}
ggplot(cloud, aes(D, Rain)) +
  geom_point() +
  geom_smooth()
```

```{r}
ms.1 <- lm(Rain ~ D, data = cloud)
summary(ms.1)
```

```{r}
plot(ms.1)
```


```{r}
residualPlots(ms.1)
```
```{r}
ggplot(cloud, aes(x=S, y=Rain)) +
  geom_point() +
  geom_smooth()
```

```{r}
ms.2 <- lm(Rain ~ S, data=cloud)
summary(ms.2)
```


```{r}
plot(ms.2)
```

```{r}
residualPlots(ms.2)
```



```{r}
ms.3 <- lm(Rain ~ log(S), data=cloud)
summary(ms.3)
```

```{r}
ggplot(cloud, aes(x=log(S), y=Rain)) +
  geom_point() +
  geom_smooth()
```


```{r}
plot(ms.3)
```

```{r}
residualPlots(ms.3)
```





```{r}
ms.4 <- lm(log(Rain) ~ log(S), data=cloud)
summary(ms.4)
```

```{r}
ggplot(cloud, aes(x=log(S), y=log(Rain))) +
  geom_point() +
  geom_smooth()
```



```{r}
plot(ms.4)
```

```{r}
residualPlots(ms.4)
```



```{r}
mc.1 <- lm(Rain ~ C, data=cloud)
summary(mc.1)
```

```{r}
ggplot(cloud, aes(x=C, y=Rain)) +
  geom_point() +
  geom_smooth()
```


```{r}
plot(mc.1)
```


```{r}
residualPlots(mc.1)
```






```{r}
mc.2 <- lm(log(Rain) ~ C, data=cloud)
summary(mc.2)
```


```{r}
ggplot(cloud, aes(x=C, y=log(Rain) )) +
  geom_point() +
  geom_smooth()
```


```{r}
plot(mc.2)
```


```{r}
residualPlots(mc.2)
```




```{r}
mc.3 <- lm(log(Rain) ~ log(C), data=cloud)
summary(mc.3)
```




```{r}
ggplot(cloud, aes(x=log(C), y=log(Rain))) +
  geom_point() +
  geom_smooth()
```


```{r}
plot(mc.3)
```


```{r}
residualPlots(mc.3)
```



```{r}
mp.1 <- lm(Rain ~ P, data=cloud)
summary(mp.1)
```


```{r}
ggplot(cloud, aes(x=P, y=Rain)) +
  geom_point() +
  geom_smooth()
```




```{r}
mp.2 <- lm(log(Rain) ~ P, data=cloud)
summary(mp.2)
```


```{r}
ggplot(cloud, aes(x=P, y=log(Rain))) +
  geom_point() +
  geom_smooth()
```



```{r}
mp.3 <- lm(log(Rain) ~ log(P), data=cloud)
summary(mp.3)
```



```{r}
mp.4 <- lm(Rain ~ log(C), data=cloud)
summary(mp.3)
```


```{r}
ggplot(cloud, aes(x=log(P), y=Rain)) +
  geom_point() +
  geom_smooth()
```



```{r}
me.1 <- lm(Rain ~ E, data=cloud)
summary(mc.3)
```


```{r}
ggplot(cloud, aes(E)) +
  geom_bar()
```




```{r}
m1 <- lm(Rain ~ A, data=cloud)
summary(m1)
```




```{r}
plot(m1)
```

=======



### Note
### use the methods of Ch. 10 to suggest a "best" model)




## Problem 10.3
<!-----  Use vif ------> 

```{r}
mantel
```


```{r}
plot(mantel)
```


```{r}
model <- lm(Y ~ X1 + X2 + X3, data=mantel)
summary(model)
```
```{r}
v <- vif(model)
rsqrd <- (v - 1) / v
rsqrd
```

```{r}
forward <- lm(Y ~ 1, data=mantel)
step(forward, scope = ~ X1 + X2 + X3, direction="forward")


```

```{r}
backward = lm(Y ~ X1 + X2 + X3, data=mantel)
step(backward, scope = ~ 1, direction="backward")
```



## Problem 10.5

```{r}
dwaste
```

```{r}
plot(dwaste)
```

```{r}
m0 <- lm(O2UP ~ . - Day, data= dwaste)
summary(m0)
```
```{r}
invResPlot(m0)
```

```{r}
summary(powerTransform(m0))
```

```{r}
boxCox(m0)
```



```{r}
v <- vif(m0)
rsqrd <- (v - 1) / v
rsqrd

```


```{r}
#AIC(m0)

stopifnot(all.equal(AIC(m0),
                         AIC(logLik(m0))))
```

```{r}
BIC(m0)
```


```{r}
step(m0, scope = ~ 1, direction = "backward")
```
```{r}
m1 <- lm(O2UP ~ 1, data=dwaste)
step(m1, scope = ~ BOD + TKN + TS + TVS + COD , direction = "forward")
```

```{r}
invResPlot(m1)
```


```{r}

mo.1 <- lm(O2UP ~ COD , data=dwaste)
AIC(mo.1)
BIC(mo.1)
```


```{r}
mo.2 <- lm(log(O2UP) ~ COD, data=dwaste)
AIC(mo.2)
BIC(mo.2)
```

```{r}
AIC(m0, mo.1)
```

```{r}
BIC(m0, mo.1)
```

```{r}
invResPlot(lm(O2UP ~ COD , data=dwaste))
```


```{r}
summary(powerTransform(mo.1))
```

```{r}
boxCox(mo.1)
```

