---
title: "Homework 6"
author: "Devin Etcitty"
date: "4/2/2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### STAT4205
#### dce2108


```{r message = FALSE, warning = FALSE}
library(alr4)
library(ggplot2)
library(tidyverse)
```

<!--- Chapter 7: Variances
--->
#### Problem 7.6
##### 7.6.1 - 7.6.4
<!--- Quadtratic Regression --->
stopping dataframe

heteroscedastic
homosecdastic

What are theset erms?

```{r}
dim(stopping)
```

```{r}
names(stopping)
```

```{r}
sapply(stopping, class)
```



```{r}
head(stopping)
```


```{r}
plot(stopping)
```

```{r}
qd <- lm(Distance ~ Speed + I(Speed^2),data=stopping)
summary(qd)
```
```{r}
p1 <- lm(Distance ~ poly(Speed, 2, raw=TRUE), data = stopping)
summary(p1)
```
```{r}
print(plot(Effect("Speed", p1)))
```
```{r}

mod2 <- lm(Y ~ X1 + X2 + I(X1^2) + I(X2^2) +  X1:X2, data=cakes)
summary(mod2)

```
```{r}
plot(mod2)
```

```{r}
vcov(mod2)
```
```{r}
sqrt(diag(vcov(mod2)))
```
```{r}
summary(mod2)$coef
```


```{r}
z <- with(cakes, polym(X1, X2, degree=2, raw=TRUE))
#summary(z)
model.matrix(~ z)
```



```{r}
ggplot(stopping, aes(Speed, Distance)) +
  geom_point()
```


###### 7.6.1
This graph supports a quadratic regression model because the graph has
a curve and less linear.

###### 7.6.2
<!---- Constant variance  ----> 

###### 7.6.3

###### 7.6.4



```{r}
head(stopping)


summary(stopping)
```


#### Problem 7.8
<!--- Jevons's gold coins--->
jevons dataframe

```{r}
dim(jevons)
```

```{r}
names(jevons)
```

```{r}
sapply(jevons, class)
```



```{r}
head(jevons)

summary(jevons)

```


```{r}
plot(jevons)
```

```{r}
ggplot(jevons, aes(Age, Weight)) +
  geom_point()
```



```{r}
ggplot(jevons, aes(Age, SD)) +
  geom_point()
```


```{r}
model.1 <- lm(SD ~ Age, data=jevons)
wts <- (nrow(jevons) * fitted(lm(abs(residuals(model.1)) ~ jevons$SD))^2) / (jevons$SD)^2
model2 <- lm(SD ~ Age, data=jevons, weights=wts)

plot(model2)
```


```{r}
summary(model2)
```


```{r}
summary(jevons)
```


#### Problem 7.12
<!--- Regression Modeling --->
mile dataframe

```{r}
head(mile)
```


```{r}
plot(mile)
```

```{r}

summary(mile)
```

```{r}
ggplot(mile, aes(Year, Time, color=Gender)) +
  geom_point() +
  geom_smooth(method=)
```



<!--- Chapter 8: Transformations --->

#### Problem 8.1
<!--- --->
baeskel dataframe

```{r}
dim(baeskel)
```

```{r}
names(baeskel)
```


```{r}
sapply(baeskel, class)
```


```{r}
head(baeskel)
```


```{r}
plot(baeskel)
```


#### Problem 8.2
<!--- --->
stopping dataframe

```{r}
dim(stopping)
```


```{r}
names(stopping)
```

```{r}
sapply(stopping, class)
```


```{r}
head(stopping)
```


```{r}
plot(stopping)
```


```{r}
summary(stopping)
```


#### Problem 8.3
<!--- Automatic Choice of Transformation --->
water dataframe

```{r}
dim(water)
```


```{r}
names(water)
```


```{r}
sapply(water, class)
```



```{r}
head(water)
```


```{r}
plot(water)
```

```{r}

```


