---
title: "Homework 5"
author: "Devin Etcitty"
output:
  pdf_document: default
  html_document: default
course: STAT4205
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### STAT4205
#### dce2108


```{r message = FALSE, warning = FALSE}
library(alr4)
```

<!--- --->

#### Problem 6.1
<!--- F-test multiple models --->
UN11 dataframe
```{r}

model6.6 <- lm(lifeExpF ~ 1, data=UN11)
model6.7 <- lm(lifeExpF ~ group,  data=UN11)



summary(model6.6)

summary(model6.7)

anova(model6.6, model6.7)
```

#### Problem 6.2
<!--- No model between (6.7) vs (6.8) --->
```{r}
model6.7 <- lm(lifeExpF ~ group,  data=UN11)
model6.8 <- lm(lifeExpF ~ log(ppgdp),  data=UN11)

summary(model6.7)
summary(model6.8)

anova(model6.7, model6.8)
```



#### Problem 6.3
<!--- --->
```{r}
model6.7 <- lm(lifeExpF ~ group,  data=UN11)
model6.9 <- lm(lifeExpF ~ group + log(ppgdp),  data=UN11)

summary(model6.7)
summary(model6.9)

anova(model6.7, model6.9)

anova(model6.9, model6.7)

```


#### Problem 6.4
<!--- --->
UN11
```{r}
nullHyp <- lm(lifeExpF ~ log(ppgdp) + group:log(ppgdp), data=UN11)
alterHyp <- lm(lifeExpF ~ group + log(ppgdp) + group:log(ppgdp), data=UN11)

summary(nullHyp)
summary(alterHyp)
```



#### Problem 6.5
<!--- --->
UN11
```{r}
paraReg <- lm(lifeExpF ~ group + log(ppgdp), data = UN11)
summary(paraReg)$coeff
summary(paraReg)
```



#### Problem 6.7
<!--- --->
fuel2001
```{r}
model6.22 <- lm(FuelC ~ Tax + Drivers + Income + log(Miles), data=fuel2001)
model6.23 <- lm(FuelC~ log(Miles) + Income + Drivers + Tax, data=fuel2001)

summary(model6.22)
summary(model6.23)

anova(model6.22, model6.23)
```


#### Problem 6.14
<!--- Testing for lack-of-fit --->
MinnLand
```{r}
model <- lm(log(acrePrice) ~ year, data=MinnLand)
summary(model)
```



#### Problem 6.18
<!--- Windmill data --->
wm2
```{r}
plot(wm2)
```

